### PR TITLE
Fix nuget push

### LINKED ISSUE #1: Nuget push fails in CI
The workflow reports push to nuget.org fails because of duplicate version.

### PR DESCRIPTION
**Pull request by KuraiAndras**
Closes #1

### CODE REVIEW

**Comment by ThomasArdal** [comment]
Appreciate the PR 👍 But, I believe this should be fixed by automatically incrementing the NuGet version on every build. I haven't looked into how this is done with GitHub Actions yet. I would love your input if you know a good way to do it.

**Comment by KuraiAndras** [comment]
This way when you increase the version in the project csproj the pipeline pushes the new version. This way you have more control over when and which version you push

**Comment by ThomasArdal** [comment]
Do you know if it’s possible to have 1.0 as static part of the version. And then include a build number in the end? 1.0.build. Then rather than having to increment the version, every successful build would go to nuget.

**Comment by ThomasArdal** [comment]
I think this would do it:

```
run: dotnet pack -c Release -o out /p:Version=1.0.$GITHUB_RUN_NUMBER
```

Then I can update the `1.0` part when I feel like it but always have the version generate a new one and publish to NuGet.

**Comment by KuraiAndras** [comment]
That is a solution but then you might create unwanted versions. For example when you just want to update the documentation you might not want a new version to be created. If you want to increment the versions that way you might want to create some release branch and run the pipeline there

**Comment by ThomasArdal** [comment]
I totally understand your point. For a project like this, I believe publishing on every push is fine 👍

**Comment by KuraiAndras** [comment]
done

**Comment by ThomasArdal** [comment]
I think you updated the wrong step. It's the build step that needs the version property ;)

**Comment by ThomasArdal** [comment]
I think we need a way to tell Actions not to publish the NuGet package when building PRs.

**Comment by KuraiAndras** [comment]
How about 2 workflows? One runs on prs and only does dotnet build, and the current workflow only runs on push to master?

**Comment by KuraiAndras** [comment]
Also I have no idea why this fails now

**Comment by ThomasArdal** [comment]
This is definitely a learning experience for me. I tried updating the PR but my push for Actions-related files are rejected for some reason. Can you try adding the following step:

```yaml
- name: debug output
  run: echo ${{ github.ref }}
```

I'm hoping that this make it possible to identify when the build is a master build and when it is a PR build. If so, we can make a conditional NuGet publish step.

**Comment by KuraiAndras** [comment]
It outputs:
```
refs/pull/2/merge
```
So it seems possible to identify whether the workflow is running on a pr

**Comment by ThomasArdal** [comment]
Can you output this value in debug output: `${{ github.event_name }}`

**Comment by ThomasArdal** [comment]
I think this will work:

```yaml
- name: Push to nuget.org
  run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
  if: ${{ github.event_name == 'push' }}
```

**Comment by ThomasArdal** [comment]
Yay it worked: https://www.nuget.org/packages/RickrollingMiddleware/1.0.22

Thank you very much for your help. This has been a fun and educational experience 👍

**Pull request merged**
